CREATE TABLE ACCOUNT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE POST(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(16) NOT NULL,
	SLUG VARCHAR(255) NOT NULL,
	CONTENT TEXT NOT NULL,
	ACCOUNT_ID BIGINT REFERENCES ACCOUNT
);
